name: on1OS Build CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      DEBIAN_FRONTEND: noninteractive
      CI: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          wget \
          curl \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          libncurses5-dev \
          pkg-config \
          libkmod-dev \
          rsync \
          tar \
          xz-utils \
          gzip \
          cpio \
          unzip \
          device-tree-compiler \
          u-boot-tools \
          mtools \
          dosfstools \
          xorriso \
          genisoimage \
          isolinux \
          syslinux-utils \
          grub-pc-bin \
          grub-efi-amd64-bin \
          autotools-dev \
          autoconf \
          automake \
          libtool \
          gettext \
          gettext-base \
          autopoint \
          fonts-dejavu-core \
          dracut \
          dracut-core \
          tpm2-tools \
          cryptsetup \
          python3 \
          python3-dev \
          python3-setuptools \
          libfuse3-dev \
          libfuse-dev \
          fuse3 \
          libzfslinux-dev \
          ffmpeg \
          imagemagick
          
    - name: Setup build environment
      run: make setup
      
    - name: Generate branding assets
      run: make branding
      
    - name: Build kernel
      run: make kernel
      
    - name: Build rootfs
      run: make rootfs
      
    - name: Build initramfs
      run: make initramfs
      
    - name: Build bootloader
      run: make bootloader
      
    - name: Create ISO
      run: make iso
      
    - name: Verify build outputs
      run: |
        echo "Checking build outputs..."
        ls -la build/
        [ -f "build/on1OS.iso" ] && echo "✅ ISO created successfully" || echo "❌ ISO not found"
        [ -f "build/iso/vmlinuz" ] && echo "✅ Kernel found" || echo "❌ Kernel not found"
        [ -f "build/iso/initrd.img" ] && echo "✅ Initramfs found" || echo "❌ Initramfs not found"
        [ -d "build/iso/rootfs" ] && echo "✅ Rootfs found" || echo "❌ Rootfs not found"
        [ -d "build/branding" ] && echo "✅ Branding assets generated" || echo "❌ Branding assets missing"
        [ -d "build/iso/boot/grub/themes/on1os" ] && echo "✅ GRUB theme found" || echo "❌ GRUB theme missing"
        
    - name: Generate build artifacts info
      run: |
        echo "Build completed on: $(date)" > build-info.txt
        echo "Kernel version: $(grep KERNEL_VERSION Makefile | cut -d'=' -f2 | tr -d ' ')" >> build-info.txt
        echo "Buildroot version: $(grep BUILDROOT_VERSION Makefile | cut -d'=' -f2 | tr -d ' ')" >> build-info.txt
        if [ -f "build/on1OS.iso" ]; then
          echo "ISO size: $(du -h build/on1OS.iso | cut -f1)" >> build-info.txt
          echo "ISO checksum: $(sha256sum build/on1OS.iso | cut -d' ' -f1)" >> build-info.txt
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: on1OS-build-artifacts
        path: |
          build/on1OS.iso
          build-info.txt
          build/iso/vmlinuz
          build/iso/initrd.img
          build/branding/previews/
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: on1OS-build-logs
        path: |
          build/
          *.log
        retention-days: 7

  test:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: on1OS-build-artifacts
        
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86
        
    - name: Test ISO boot (quick test)
      run: |
        ls -lh build/on1OS.iso
        if [ ! -f "build/on1OS.iso" ]; then
          echo "❌ ISO file not found in workspace. Check artifact upload/download steps."
          exit 1
        fi
        timeout 60s qemu-system-x86_64 \
          -m 1024 \
          -cdrom build/on1OS.iso \
          -boot d \
          -nographic \
          -serial stdio || true
        echo "Boot test completed"
        
    - name: Validate ISO structure
      run: |
        ls -lh build/on1OS.iso
        if [ ! -f "build/on1OS.iso" ]; then
          echo "❌ ISO file not found in workspace. Check artifact upload/download steps."
          exit 1
        fi
        sudo mkdir -p /mnt/iso
        sudo mount -o loop build/on1OS.iso /mnt/iso
        echo "ISO contents:"
        ls -la /mnt/iso/
        [ -f "/mnt/iso/vmlinuz" ] && echo "✅ Kernel found in ISO" || echo "❌ Kernel missing in ISO"
        [ -f "/mnt/iso/initrd.img" ] && echo "✅ Initramfs found in ISO" || echo "❌ Initramfs missing in ISO"
        [ -d "/mnt/iso/boot/grub/themes/on1os" ] && echo "✅ GRUB theme found in ISO" || echo "❌ GRUB theme missing in ISO"
        [ -f "/mnt/iso/boot/grub/themes/on1os/background.png" ] && echo "✅ Custom background found" || echo "❌ Custom background missing"
        sudo umount /mnt/iso
